import { Router } from "express";
import { authRouter } from "./auth/auth.routes";
import { patientsRouter } from "./patients/patients.routes";
import { testsRouter } from "./tests/tests.routes";
import { ordersRouter } from "./orders/orders.routes";
import { reportsRouter } from "./reports/reports.routes";
import { invoicesRouter } from "./invoices/invoices.routes";
import { dashboardRouter } from "./dashboard/dashboard.routes";
import { usersRouter } from "./users/users.routes";
import { branchesRouter } from "./branches/branches.routes";
import { tenantRouter } from "./tenant/tenant.routes";
import { publicRouter } from "./public/public.routes";
import { uploadsRouter } from "./uploads/uploads.routes";
import { referrersRouter } from "./referrers/referrers.routes";
import { appointmentsRouter } from "./appointments/appointments.routes";
import { consultationsRouter } from "./consultations/consultations.routes";
import { prescriptionsRouter } from "./prescriptions/prescriptions.routes";
import { doctorSchedulesRouter } from "./doctor-schedules/doctor-schedules.routes";
import { icdRouter } from "./icd/icd.routes";
import { medicinesRouter } from "./medicines/medicines.routes";
import { suppliersRouter } from "./suppliers/suppliers.routes";
import { stockRouter } from "./stock/stock.routes";
import { pharmacyRouter } from "./pharmacy/pharmacy.routes";
import { wardsRouter } from "./wards/wards.routes";
import { bedsRouter } from "./beds/beds.routes";
import { admissionsRouter } from "./admissions/admissions.routes";
import { ipdChargesRouter } from "./ipd-charges/ipd-charges.routes";
import { nursingNotesRouter } from "./nursing-notes/nursing-notes.routes";
import { doctorVisitsRouter } from "./doctor-visits/doctor-visits.routes";
import { expensesRouter } from "./expenses/expenses.routes";
import { bloodBankRouter } from "./blood-bank/blood-bank.routes";
import { ambulanceRouter } from "./ambulance/ambulance.routes";
import { vaccinationRouter } from "./vaccination/vaccination.routes";
import { otRouter } from "./ot/ot.routes";
import { cashCloseRouter } from "./cash-close/cash-close.routes";
import { pettyCashRouter } from "./petty-cash/petty-cash.routes";
import { commissionsRouter } from "./commissions/commissions.routes";
import { feedbackRouter, publicFeedbackRouter } from "./feedback/feedback.routes";
import { healthCardsRouter } from "./health-cards/health-cards.routes";
import { smsRouter } from "./sms/sms.routes";
import { noticesRouter } from "./notices/notices.routes";
import { tokenBoardRouter } from "./token-board/token-board.routes";
import { hrRouter } from "./hr/hr.routes";
import { corporateClientsRouter, corporateStatementsRouter } from "./corporate-clients/corporate-clients.routes";
import {
  subscriptionPlansRouter,
  publicSubscriptionPlansRouter,
  platformSubscriptionPlansRouter,
} from "./subscription-plans/subscription-plans.routes";
import { subscriptionInvoicesRouter } from "./subscription-invoices/subscription-invoices.routes";
import { platformRouter } from "./platform/platform.routes";
import { signupRouter } from "./signup/signup.routes";
import { permissionsRouter } from "./permissions/permissions.routes";
import { featuresRouter, platformFeaturesRouter } from "./features/features.routes";
import { supportRouter } from "./support/support.routes";
import { searchRouter } from "./search/search.routes";

export const router = Router();

router.use("/auth", authRouter);
router.use("/public", publicRouter);
router.use("/patients", patientsRouter);
router.use("/tests", testsRouter);
router.use("/orders", ordersRouter);
router.use("/reports", reportsRouter);
router.use("/invoices", invoicesRouter);
router.use("/dashboard", dashboardRouter);
router.use("/users", usersRouter);
router.use("/branches", branchesRouter);
router.use("/tenant", tenantRouter);
router.use("/uploads", uploadsRouter);
router.use("/referrers", referrersRouter);
router.use("/appointments", appointmentsRouter);
router.use("/consultations", consultationsRouter);
router.use("/prescriptions", prescriptionsRouter);
router.use("/doctor-schedules", doctorSchedulesRouter);
router.use("/icd", icdRouter);
router.use("/medicines", medicinesRouter);
router.use("/suppliers", suppliersRouter);
router.use("/stock", stockRouter);
router.use("/pharmacy", pharmacyRouter);
router.use("/wards", wardsRouter);
router.use("/beds", bedsRouter);
router.use("/admissions", admissionsRouter);
router.use("/ipd-charges", ipdChargesRouter);
router.use("/nursing-notes", nursingNotesRouter);
router.use("/doctor-visits", doctorVisitsRouter);
router.use("/expenses", expensesRouter);
router.use("/blood-bank", bloodBankRouter);
router.use("/ambulance", ambulanceRouter);
router.use("/vaccination", vaccinationRouter);
router.use("/ot", otRouter);
router.use("/cash-close", cashCloseRouter);
router.use("/petty-cash", pettyCashRouter);
router.use("/commissions", commissionsRouter);
router.use("/feedback", feedbackRouter);
router.use("/public/feedback", publicFeedbackRouter);
router.use("/health-cards", healthCardsRouter);
router.use("/sms", smsRouter);
router.use("/notices", noticesRouter);
router.use("/public/token-board", tokenBoardRouter);
router.use("/hr", hrRouter);
router.use("/corporate-clients", corporateClientsRouter);
router.use("/corporate-statements", corporateStatementsRouter);
router.use("/signup", signupRouter);
router.use("/permissions", permissionsRouter);
router.use("/features", featuresRouter);
router.use("/support", supportRouter);
router.use("/search", searchRouter);
// Platform-admin feature management — mounted before the generic /platform
// router so the more specific prefix wins.
router.use("/platform", platformFeaturesRouter);
router.use("/public/plans", publicSubscriptionPlansRouter);
router.use("/subscription-plans", subscriptionPlansRouter);
router.use("/subscription-invoices", subscriptionInvoicesRouter);
// Mount /platform/plans BEFORE /platform so Express tries the more specific
// prefix first (the platformRouter is otherwise greedy on /platform/*).
router.use("/platform/plans", platformSubscriptionPlansRouter);
router.use("/platform", platformRouter);
