import dayjs from "dayjs";
import { Prisma, SubscriptionInvoiceStatus, SubscriptionStatus } from "@prisma/client";
import { prisma } from "../config/db";
import { notify } from "../utils/notify";

const D = (n: number | string | Prisma.Decimal) => new Prisma.Decimal(n);

/**
 * Days a tenant is allowed to stay PAST_DUE before we auto-suspend them.
 * Tunable later via env. Conservative default — 7 days is what most BD
 * SaaS products use before locking accounts.
 */
const GRACE_DAYS = 7;
/**
 * Trial users get a heads-up this many days before the trial expires.
 */
const TRIAL_REMINDER_DAYS = 3;

// ── Helpers ───────────────────────────────────────────────

const nextInvoiceNumber = async (tenantId: string): Promise<string> => {
  const prefix = `SUB-${dayjs().format("YYMM")}-`;
  const last = await prisma.subscriptionInvoice.findFirst({
    where: { tenantId, invoiceNumber: { startsWith: prefix } },
    orderBy: { invoiceNumber: "desc" },
    select: { invoiceNumber: true },
  });
  const seq = last ? Number(last.invoiceNumber.slice(prefix.length)) + 1 : 1;
  return `${prefix}${String(seq).padStart(4, "0")}`;
};

// ── Steps ─────────────────────────────────────────────────

/**
 * For every ACTIVE subscription whose `nextBillingDate <= now`, generate the
 * invoice for the upcoming period IF one doesn't already exist for that
 * period. Then advance `nextBillingDate` by one cycle. Idempotent — re-running
 * the same day finds the invoice already exists and is a no-op.
 */
export async function generateDueInvoices(now: Date = new Date()) {
  const subs = await prisma.subscription.findMany({
    where: {
      status: "ACTIVE",
      nextBillingDate: { lte: now },
    },
    include: {
      planConfig: true,
      tenant: { select: { id: true, isPlatform: true, name: true, contactPhone: true } },
    },
  });

  let created = 0, skipped = 0;
  for (const sub of subs) {
    if (sub.tenant.isPlatform) {
      skipped++; continue;
    }
    if (!sub.planConfig) {
      // Tenant has no linked plan — skip until ops fixes it.
      skipped++; continue;
    }
    const cycleStart = dayjs(sub.nextBillingDate ?? now).startOf("day");
    let cycleEnd: dayjs.Dayjs;
    if (sub.billingCycle === "YEARLY") cycleEnd = cycleStart.add(1, "year").subtract(1, "day").endOf("day");
    else if (sub.billingCycle === "QUARTERLY") cycleEnd = cycleStart.add(3, "month").subtract(1, "day").endOf("day");
    else cycleEnd = cycleStart.add(1, "month").subtract(1, "day").endOf("day");

    // Skip if we already invoiced this exact period.
    const existing = await prisma.subscriptionInvoice.findFirst({
      where: {
        tenantId: sub.tenantId,
        periodFrom: cycleStart.toDate(),
        periodTo: cycleEnd.toDate(),
      },
      select: { id: true },
    });
    if (existing) {
      // Just advance nextBillingDate to the next cycle so we don't loop.
      await prisma.subscription.update({
        where: { tenantId: sub.tenantId },
        data: { nextBillingDate: cycleEnd.add(1, "day").startOf("day").toDate() },
      });
      skipped++; continue;
    }

    const unitPrice =
      sub.billingCycle === "YEARLY"
        ? Number(sub.planConfig.yearlyPrice)
        : sub.billingCycle === "QUARTERLY"
          ? Number(sub.planConfig.monthlyPrice) * 3
          : Number(sub.planConfig.monthlyPrice);

    const subtotal = D(unitPrice);
    const totalAmount = subtotal;
    const dueDate = dayjs(now).add(14, "day").startOf("day").toDate();
    const invoiceNumber = await nextInvoiceNumber(sub.tenantId);

    await prisma.$transaction([
      prisma.subscriptionInvoice.create({
        data: {
          tenantId: sub.tenantId,
          invoiceNumber,
          periodFrom: cycleStart.toDate(),
          periodTo: cycleEnd.toDate(),
          dueDate,
          status: "ISSUED",
          planCode: sub.planConfig.code,
          planName: sub.planConfig.name,
          billingCycle: sub.billingCycle,
          subtotal, discountAmount: D(0), totalAmount,
          paidAmount: D(0), dueAmount: totalAmount,
          notes: "Auto-generated by lifecycle cron",
          lines: {
            create: [{
              description: `${sub.planConfig.name} subscription · ${cycleStart.format("DD MMM YYYY")} – ${cycleEnd.format("DD MMM YYYY")}`,
              qty: 1, unitPrice: subtotal, amount: subtotal,
            }],
          },
        },
      }),
      // Advance nextBillingDate
      prisma.subscription.update({
        where: { tenantId: sub.tenantId },
        data: {
          nextBillingDate: cycleEnd.add(1, "day").startOf("day").toDate(),
          billingCycleStart: cycleStart.toDate(),
          billingCycleEnd: cycleEnd.toDate(),
        },
      }),
      prisma.subscriptionEvent.create({
        data: {
          tenantId: sub.tenantId,
          eventType: "INVOICE_GENERATED",
          notes: `Invoice ${invoiceNumber} for ${cycleStart.format("DD MMM YYYY")} – ${cycleEnd.format("DD MMM YYYY")}`,
        },
      }),
    ]);

    // Notify the tenant the invoice is ready (fire-and-forget SMS).
    if (sub.tenant.contactPhone) {
      void notify({
        tenantId: sub.tenantId,
        to: sub.tenant.contactPhone,
        body: `Your DMS subscription invoice ${invoiceNumber} (৳${Number(totalAmount).toFixed(0)}) is ready. Due ${dayjs(dueDate).format("DD MMM")}.`,
        relatedTo: `SUB_INVOICE:${invoiceNumber}`,
      });
    }

    created++;
  }
  return { created, skipped, scanned: subs.length };
}

/**
 * Mark ISSUED / PARTIALLY_PAID invoices as OVERDUE once past `dueDate`.
 */
export async function markOverdueInvoices(now: Date = new Date()) {
  const r = await prisma.subscriptionInvoice.updateMany({
    where: {
      status: { in: ["ISSUED", "PARTIALLY_PAID"] },
      dueDate: { lt: now },
    },
    data: { status: SubscriptionInvoiceStatus.OVERDUE },
  });
  return { marked: r.count };
}

/**
 * Move tenants from TRIAL → PAST_DUE once `trialEndsAt` has passed AND no
 * invoice has been paid yet. They get a grace window before SUSPEND.
 */
export async function endExpiredTrials(now: Date = new Date()) {
  const subs = await prisma.subscription.findMany({
    where: {
      status: "TRIAL",
      trialEndsAt: { lt: now },
    },
    select: { tenantId: true, tenant: { select: { contactPhone: true, name: true } } },
  });
  let transitioned = 0;
  for (const s of subs) {
    await prisma.subscription.update({
      where: { tenantId: s.tenantId },
      data: { status: SubscriptionStatus.PAST_DUE },
    });
    await prisma.subscriptionEvent.create({
      data: {
        tenantId: s.tenantId,
        eventType: "TRIAL_ENDED",
        notes: "Trial expired — moved to PAST_DUE pending first payment",
      },
    });
    if (s.tenant.contactPhone) {
      void notify({
        tenantId: s.tenantId,
        to: s.tenant.contactPhone,
        body: `Your DMS trial has ended. Pay your first subscription invoice in the next ${GRACE_DAYS} days to avoid suspension.`,
        relatedTo: "TRIAL_ENDED",
      });
    }
    transitioned++;
  }
  return { transitioned };
}

/**
 * Send "trial ending in 3 days" SMS to tenants currently on TRIAL whose
 * trial ends in exactly TRIAL_REMINDER_DAYS days. Once-per-tenant per trial
 * via the SubscriptionEvent log.
 */
export async function sendTrialReminders(now: Date = new Date()) {
  const target = dayjs(now).add(TRIAL_REMINDER_DAYS, "day");
  const dayStart = target.startOf("day").toDate();
  const dayEnd = target.endOf("day").toDate();

  const subs = await prisma.subscription.findMany({
    where: {
      status: "TRIAL",
      trialEndsAt: { gte: dayStart, lte: dayEnd },
    },
    select: { tenantId: true, trialEndsAt: true, tenant: { select: { contactPhone: true, name: true } } },
  });

  let sent = 0;
  for (const s of subs) {
    // Idempotency — skip if we already sent the reminder for this trial.
    const already = await prisma.subscriptionEvent.findFirst({
      where: { tenantId: s.tenantId, eventType: "TRIAL_REMINDER_SENT" },
    });
    if (already) continue;

    if (s.tenant.contactPhone) {
      void notify({
        tenantId: s.tenantId,
        to: s.tenant.contactPhone,
        body: `Reminder: your DMS trial ends in ${TRIAL_REMINDER_DAYS} days (${dayjs(s.trialEndsAt).format("DD MMM")}). Upgrade to keep your data and continue.`,
        relatedTo: "TRIAL_REMINDER",
      });
    }
    await prisma.subscriptionEvent.create({
      data: {
        tenantId: s.tenantId,
        eventType: "TRIAL_REMINDER_SENT",
        notes: `Trial-ending reminder sent (T-${TRIAL_REMINDER_DAYS}d)`,
      },
    });
    sent++;
  }
  return { sent };
}

/**
 * Auto-suspend tenants whose oldest OVERDUE invoice is older than GRACE_DAYS
 * AND who aren't already SUSPENDED/CANCELLED. They keep their data — they
 * just can't log in. Re-activation happens automatically when payment lands
 * (see subscription-invoices.controller.ts → recordPayment).
 */
export async function suspendOverdueTenants(now: Date = new Date()) {
  const cutoff = dayjs(now).subtract(GRACE_DAYS, "day").toDate();
  const candidates = await prisma.subscriptionInvoice.findMany({
    where: {
      status: { in: ["OVERDUE", "PARTIALLY_PAID"] },
      dueDate: { lt: cutoff },
    },
    select: { tenantId: true, invoiceNumber: true },
    distinct: ["tenantId"],
  });

  let suspended = 0;
  for (const c of candidates) {
    const sub = await prisma.subscription.findUnique({
      where: { tenantId: c.tenantId },
      select: { status: true, tenant: { select: { isPlatform: true, contactPhone: true } } },
    });
    if (!sub) continue;
    if (sub.tenant.isPlatform) continue;
    if (sub.status === "SUSPENDED" || sub.status === "CANCELLED") continue;

    await prisma.subscription.update({
      where: { tenantId: c.tenantId },
      data: { status: SubscriptionStatus.SUSPENDED, suspendedAt: new Date() },
    });
    await prisma.subscriptionEvent.create({
      data: {
        tenantId: c.tenantId,
        eventType: "AUTO_SUSPENDED",
        notes: `Suspended after ${GRACE_DAYS}+ days overdue (invoice ${c.invoiceNumber})`,
      },
    });
    if (sub.tenant.contactPhone) {
      void notify({
        tenantId: c.tenantId,
        to: sub.tenant.contactPhone,
        body: `Your DMS subscription has been suspended for non-payment. Settle outstanding invoices to restore access.`,
        relatedTo: "AUTO_SUSPENDED",
      });
    }
    suspended++;
  }
  return { suspended };
}

/**
 * Run all five steps as one daily pass. Errors in one step don't stop the
 * others — they're logged and the others continue.
 */
export async function runSubscriptionLifecycle(now: Date = new Date()) {
  const safe = async <T>(label: string, fn: () => Promise<T>): Promise<T | { error: string }> => {
    try {
      return await fn();
    } catch (err) {
      console.error(`[sub-lifecycle:${label}]`, err);
      return { error: (err as Error).message };
    }
  };
  const a = await safe("generate", () => generateDueInvoices(now));
  const b = await safe("overdue",  () => markOverdueInvoices(now));
  const c = await safe("trials",   () => endExpiredTrials(now));
  const d = await safe("trialRem", () => sendTrialReminders(now));
  const e = await safe("suspend",  () => suspendOverdueTenants(now));
  return { generate: a, overdue: b, trials: c, trialRem: d, suspend: e };
}

// ── Scheduler (same pattern as IPD job: hourly tick, once-per-day guard) ──

let lastRunDate: string | null = null;
let timer: ReturnType<typeof setInterval> | null = null;

export function startSubscriptionLifecycle() {
  if (timer) return;
  const tick = async () => {
    try {
      // Create dayjs object for Dhaka time (UTC+6)
      let dhakaNow = dayjs();
      dhakaNow = dhakaNow.add(6, "hour");
      // Run once per day around 01:00 Dhaka (= 19:00 UTC).
      const dateKey = dhakaNow.format("YYYY-MM-DD");
      const hour = dhakaNow.hour();
      if ((hour === 1 || hour === 2) && lastRunDate !== dateKey) {
        const r = await runSubscriptionLifecycle();
        lastRunDate = dateKey;
        console.log(`[sub-lifecycle] ${dateKey}`, JSON.stringify(r));
      }
    } catch (err) {
      console.error("[sub-lifecycle] error", err);
    }
  };
  void tick();
  timer = setInterval(tick, 60 * 60 * 1000);
}

export function stopSubscriptionLifecycle() {
  if (timer) clearInterval(timer);
  timer = null;
}
